"""initial schema

Revision ID: 182010f00859
Revises: 
Create Date: 2026-05-30 21:32:19.765226
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '182010f00859'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_user',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('cognito_sub', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_app_user_cognito_sub'), 'app_user', ['cognito_sub'], unique=True)
    op.create_index(op.f('ix_app_user_email'), 'app_user', ['email'], unique=False)
    op.create_table('catalogue_vendor',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('last_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('control',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=80), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('risk',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=80), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('layer', sa.Enum('TECHNICAL_SECURITY', 'GOVERNANCE_RIGHTS', 'ADVERSARIAL_THREAT', name='risk_layer'), nullable=False),
    sa.Column('source', sa.Enum('OWASP_LLM', 'NIST_AI_RMF', 'ISO_42001', 'ISO_42005', 'MITRE_ATLAS', 'INTERNAL', name='risk_source'), nullable=False),
    sa.Column('source_ref', sa.String(length=120), nullable=True),
    sa.Column('typical_triggers', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index(op.f('ix_risk_layer'), 'risk', ['layer'], unique=False)
    op.create_table('tenant',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('audit_event',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actor_user_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=120), nullable=False),
    sa.Column('entity_type', sa.String(length=60), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('source_ip', postgresql.INET(), nullable=True),
    sa.ForeignKeyConstraint(['actor_user_id'], ['app_user.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_event_action'), 'audit_event', ['action'], unique=False)
    op.create_index(op.f('ix_audit_event_entity_id'), 'audit_event', ['entity_id'], unique=False)
    op.create_index(op.f('ix_audit_event_occurred_at'), 'audit_event', ['occurred_at'], unique=False)
    op.create_index(op.f('ix_audit_event_tenant_id'), 'audit_event', ['tenant_id'], unique=False)
    op.create_table('catalogue_product',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('vendor_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('taxonomy_tags', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('last_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['vendor_id'], ['catalogue_vendor.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_catalogue_product_vendor_id'), 'catalogue_product', ['vendor_id'], unique=False)
    op.create_table('control_framework_map',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('control_id', sa.UUID(), nullable=False),
    sa.Column('framework', sa.Enum('ISO_42001', 'ISO_42005', 'EU_AI_ACT', 'NIST_AI_RMF', name='framework'), nullable=False),
    sa.Column('clause_ref', sa.String(length=120), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['control_id'], ['control.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('control_id', 'framework', 'clause_ref', name='uq_control_framework_clause')
    )
    op.create_index(op.f('ix_control_framework_map_control_id'), 'control_framework_map', ['control_id'], unique=False)
    op.create_index(op.f('ix_control_framework_map_framework'), 'control_framework_map', ['framework'], unique=False)
    op.create_table('evidence',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('s3_bucket', sa.String(length=255), nullable=False),
    sa.Column('s3_key', sa.String(length=1024), nullable=False),
    sa.Column('s3_version_id', sa.String(length=255), nullable=True),
    sa.Column('content_type', sa.String(length=120), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('sha256', sa.String(length=64), nullable=True),
    sa.Column('uploaded_by_user_id', sa.UUID(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by_user_id'], ['app_user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evidence_sha256'), 'evidence', ['sha256'], unique=False)
    op.create_index(op.f('ix_evidence_tenant_id'), 'evidence', ['tenant_id'], unique=False)
    op.create_table('membership',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'REVIEWER', 'CONTRIBUTOR', 'AUDITOR_READONLY', name='user_role'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'tenant_id', name='uq_membership_user_tenant')
    )
    op.create_index(op.f('ix_membership_tenant_id'), 'membership', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_membership_user_id'), 'membership', ['user_id'], unique=False)
    op.create_table('risk_control_map',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('risk_id', sa.UUID(), nullable=False),
    sa.Column('control_id', sa.UUID(), nullable=False),
    sa.Column('strength', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['control_id'], ['control.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['risk_id'], ['risk.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('risk_id', 'control_id', name='uq_risk_control')
    )
    op.create_index(op.f('ix_risk_control_map_control_id'), 'risk_control_map', ['control_id'], unique=False)
    op.create_index(op.f('ix_risk_control_map_risk_id'), 'risk_control_map', ['risk_id'], unique=False)
    op.create_table('vendor_approval',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('catalogue_vendor_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('NOT_STARTED', 'UNDER_REVIEW', 'APPROVED', 'REJECTED', 'EXPIRED', name='approval_status'), nullable=False),
    sa.Column('valid_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('diligence_blob', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['catalogue_vendor_id'], ['catalogue_vendor.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'catalogue_vendor_id', name='uq_vendor_approval')
    )
    op.create_index(op.f('ix_vendor_approval_catalogue_vendor_id'), 'vendor_approval', ['catalogue_vendor_id'], unique=False)
    op.create_index(op.f('ix_vendor_approval_tenant_id'), 'vendor_approval', ['tenant_id'], unique=False)
    op.create_table('catalogue_fact',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('key', sa.String(length=120), nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('source_label', sa.String(length=255), nullable=True),
    sa.Column('last_checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('provenance', sa.Enum('AI_SUGGESTED', 'CATALOGUE_CURATED', 'USER_CONFIRMED', 'USER_AMENDED', name='provenance_confidence'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['catalogue_product.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_catalogue_fact_product_id'), 'catalogue_fact', ['product_id'], unique=False)
    op.create_table('catalogue_product_risk',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('risk_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['catalogue_product.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['risk_id'], ['risk.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'risk_id', name='uq_cat_product_risk')
    )
    op.create_index(op.f('ix_catalogue_product_risk_product_id'), 'catalogue_product_risk', ['product_id'], unique=False)
    op.create_index(op.f('ix_catalogue_product_risk_risk_id'), 'catalogue_product_risk', ['risk_id'], unique=False)
    op.create_table('product_approval',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('catalogue_product_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('NOT_STARTED', 'UNDER_REVIEW', 'APPROVED', 'REJECTED', 'EXPIRED', name='approval_status'), nullable=False),
    sa.Column('valid_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('diligence_blob', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['catalogue_product_id'], ['catalogue_product.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'catalogue_product_id', name='uq_product_approval')
    )
    op.create_index(op.f('ix_product_approval_catalogue_product_id'), 'product_approval', ['catalogue_product_id'], unique=False)
    op.create_index(op.f('ix_product_approval_tenant_id'), 'product_approval', ['tenant_id'], unique=False)
    op.create_table('system',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('owner_user_id', sa.UUID(), nullable=True),
    sa.Column('catalogue_vendor_id', sa.UUID(), nullable=True),
    sa.Column('catalogue_product_id', sa.UUID(), nullable=True),
    sa.Column('metadata_blob', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['catalogue_product_id'], ['catalogue_product.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['catalogue_vendor_id'], ['catalogue_vendor.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['owner_user_id'], ['app_user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_catalogue_product_id'), 'system', ['catalogue_product_id'], unique=False)
    op.create_index(op.f('ix_system_catalogue_vendor_id'), 'system', ['catalogue_vendor_id'], unique=False)
    op.create_index(op.f('ix_system_tenant_id'), 'system', ['tenant_id'], unique=False)
    op.create_table('use_case',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('system_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('purpose', sa.Text(), nullable=True),
    sa.Column('state', sa.Enum('REQUESTED', 'VENDOR_CHECK', 'PRODUCT_CHECK', 'INTAKE', 'HALTED_PROHIBITED', 'UNDER_ASSESSMENT', 'TREATMENT_PENDING', 'PENDING_AUTHORISATION', 'AUTHORISED', 'DEPLOYED', 'HELD', 'RETIRED', name='lifecycle_state'), nullable=False),
    sa.Column('eu_tier', sa.Enum('PROHIBITED', 'HIGH', 'LIMITED', 'MINIMAL', 'UNCLASSIFIED', name='eu_ai_act_tier'), nullable=False),
    sa.Column('context_blob', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['system_id'], ['system.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_use_case_state'), 'use_case', ['state'], unique=False)
    op.create_index(op.f('ix_use_case_system_id'), 'use_case', ['system_id'], unique=False)
    op.create_index(op.f('ix_use_case_tenant_id'), 'use_case', ['tenant_id'], unique=False)
    op.create_table('assessment',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('use_case_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('AIIA', 'FRIA', 'DPIA', 'MODEL_RISK', name='assessment_type'), nullable=False),
    sa.Column('parent_aiia_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'IN_REVIEW', 'APPROVED', 'NEEDS_REFRESH', name='assessment_status'), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('residual_risk_summary', sa.Text(), nullable=True),
    sa.Column('approved_by_user_id', sa.UUID(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['approved_by_user_id'], ['app_user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['parent_aiia_id'], ['assessment.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['use_case_id'], ['use_case.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assessment_parent_aiia_id'), 'assessment', ['parent_aiia_id'], unique=False)
    op.create_index(op.f('ix_assessment_tenant_id'), 'assessment', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_assessment_use_case_id'), 'assessment', ['use_case_id'], unique=False)
    op.create_table('classification',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('use_case_id', sa.UUID(), nullable=False),
    sa.Column('tier', sa.Enum('PROHIBITED', 'HIGH', 'LIMITED', 'MINIMAL', 'UNCLASSIFIED', name='eu_ai_act_tier'), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('answers_blob', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('overridden', sa.Boolean(), nullable=False),
    sa.Column('proposed_tier', sa.Enum('PROHIBITED', 'HIGH', 'LIMITED', 'MINIMAL', 'UNCLASSIFIED', name='eu_ai_act_tier'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['use_case_id'], ['use_case.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_classification_is_current'), 'classification', ['is_current'], unique=False)
    op.create_index(op.f('ix_classification_tenant_id'), 'classification', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_classification_use_case_id'), 'classification', ['use_case_id'], unique=False)
    op.create_table('lifecycle_transition',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('use_case_id', sa.UUID(), nullable=False),
    sa.Column('from_state', sa.Enum('REQUESTED', 'VENDOR_CHECK', 'PRODUCT_CHECK', 'INTAKE', 'HALTED_PROHIBITED', 'UNDER_ASSESSMENT', 'TREATMENT_PENDING', 'PENDING_AUTHORISATION', 'AUTHORISED', 'DEPLOYED', 'HELD', 'RETIRED', name='lifecycle_state'), nullable=True),
    sa.Column('to_state', sa.Enum('REQUESTED', 'VENDOR_CHECK', 'PRODUCT_CHECK', 'INTAKE', 'HALTED_PROHIBITED', 'UNDER_ASSESSMENT', 'TREATMENT_PENDING', 'PENDING_AUTHORISATION', 'AUTHORISED', 'DEPLOYED', 'HELD', 'RETIRED', name='lifecycle_state'), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actor_user_id', sa.UUID(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('triggered_by', sa.String(length=60), nullable=True),
    sa.ForeignKeyConstraint(['actor_user_id'], ['app_user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['use_case_id'], ['use_case.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lifecycle_transition_tenant_id'), 'lifecycle_transition', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_lifecycle_transition_use_case_id'), 'lifecycle_transition', ['use_case_id'], unique=False)
    op.create_table('assessment_item',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('assessment_id', sa.UUID(), nullable=False),
    sa.Column('risk_id', sa.UUID(), nullable=True),
    sa.Column('prompt', sa.Text(), nullable=True),
    sa.Column('response', sa.Text(), nullable=True),
    sa.Column('likelihood', sa.Integer(), nullable=True),
    sa.Column('severity', sa.Integer(), nullable=True),
    sa.Column('mitigation_plan', sa.Text(), nullable=True),
    sa.Column('provenance', sa.Enum('AI_SUGGESTED', 'CATALOGUE_CURATED', 'USER_CONFIRMED', 'USER_AMENDED', name='provenance_confidence'), nullable=False),
    sa.Column('ai_suggested_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessment.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['risk_id'], ['risk.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assessment_item_assessment_id'), 'assessment_item', ['assessment_id'], unique=False)
    op.create_index(op.f('ix_assessment_item_risk_id'), 'assessment_item', ['risk_id'], unique=False)
    op.create_index(op.f('ix_assessment_item_tenant_id'), 'assessment_item', ['tenant_id'], unique=False)
    op.create_table('assessment_item_control',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('item_id', sa.UUID(), nullable=False),
    sa.Column('control_id', sa.UUID(), nullable=False),
    sa.Column('coverage', sa.Enum('OPEN', 'PARTIAL', 'SATISFIED', name='coverage_status'), nullable=False),
    sa.ForeignKeyConstraint(['control_id'], ['control.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['item_id'], ['assessment_item.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assessment_item_control_control_id'), 'assessment_item_control', ['control_id'], unique=False)
    op.create_index(op.f('ix_assessment_item_control_item_id'), 'assessment_item_control', ['item_id'], unique=False)
    op.create_table('assessment_item_evidence',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('item_id', sa.UUID(), nullable=False),
    sa.Column('evidence_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['evidence_id'], ['evidence.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['item_id'], ['assessment_item.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assessment_item_evidence_evidence_id'), 'assessment_item_evidence', ['evidence_id'], unique=False)
    op.create_index(op.f('ix_assessment_item_evidence_item_id'), 'assessment_item_evidence', ['item_id'], unique=False)
    
    # --- Hand-added: guarantees autogenerate cannot express ---

    # 1. Partial unique indexes (business rules)
    op.execute("""
        CREATE UNIQUE INDEX uq_one_aiia_per_use_case
        ON assessment (use_case_id)
        WHERE type = 'AIIA'
    """)
    op.execute("""
        CREATE UNIQUE INDEX uq_current_classification
        ON classification (use_case_id)
        WHERE is_current = true
    """)

    # 2. Audit-event immutability: revoke mutation from the runtime role,
    #    and enforce append-only with a trigger (belt and braces).
    op.execute("REVOKE UPDATE, DELETE ON audit_event FROM irontrustai_app")
    op.execute("""
        CREATE OR REPLACE FUNCTION block_audit_mutation() RETURNS trigger AS $$
        BEGIN
            RAISE EXCEPTION 'audit_event is append-only';
        END;
        $$ LANGUAGE plpgsql
    """)
    op.execute("""
        CREATE TRIGGER audit_no_update
        BEFORE UPDATE OR DELETE ON audit_event
        FOR EACH ROW EXECUTE FUNCTION block_audit_mutation()
    """)

    # 3. Row-Level Security on tenant-scoped tables.
    tenant_scoped = [
        "system", "use_case", "assessment", "assessment_item",
        "classification", "evidence", "lifecycle_transition",
        "vendor_approval", "product_approval", "membership", "audit_event",
    ]
    for table in tenant_scoped:
        op.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY")
        op.execute(f"""
            CREATE POLICY tenant_isolation ON {table}
            USING (tenant_id = current_setting('app.current_tenant', true)::uuid)
        """)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # --- Reverse the hand-added guarantees first ---
    tenant_scoped = [
        "system", "use_case", "assessment", "assessment_item",
        "classification", "evidence", "lifecycle_transition",
        "vendor_approval", "product_approval", "membership", "audit_event",
    ]
    for table in tenant_scoped:
        op.execute(f"DROP POLICY IF EXISTS tenant_isolation ON {table}")
        op.execute(f"ALTER TABLE {table} DISABLE ROW LEVEL SECURITY")

    op.execute("DROP TRIGGER IF EXISTS audit_no_update ON audit_event")
    op.execute("DROP FUNCTION IF EXISTS block_audit_mutation()")

    op.execute("DROP INDEX IF EXISTS uq_current_classification")
    op.execute("DROP INDEX IF EXISTS uq_one_aiia_per_use_case")
    
    op.drop_index(op.f('ix_assessment_item_evidence_item_id'), table_name='assessment_item_evidence')
    op.drop_index(op.f('ix_assessment_item_evidence_evidence_id'), table_name='assessment_item_evidence')
    op.drop_table('assessment_item_evidence')
    op.drop_index(op.f('ix_assessment_item_control_item_id'), table_name='assessment_item_control')
    op.drop_index(op.f('ix_assessment_item_control_control_id'), table_name='assessment_item_control')
    op.drop_table('assessment_item_control')
    op.drop_index(op.f('ix_assessment_item_tenant_id'), table_name='assessment_item')
    op.drop_index(op.f('ix_assessment_item_risk_id'), table_name='assessment_item')
    op.drop_index(op.f('ix_assessment_item_assessment_id'), table_name='assessment_item')
    op.drop_table('assessment_item')
    op.drop_index(op.f('ix_lifecycle_transition_use_case_id'), table_name='lifecycle_transition')
    op.drop_index(op.f('ix_lifecycle_transition_tenant_id'), table_name='lifecycle_transition')
    op.drop_table('lifecycle_transition')
    op.drop_index(op.f('ix_classification_use_case_id'), table_name='classification')
    op.drop_index(op.f('ix_classification_tenant_id'), table_name='classification')
    op.drop_index(op.f('ix_classification_is_current'), table_name='classification')
    op.drop_table('classification')
    op.drop_index(op.f('ix_assessment_use_case_id'), table_name='assessment')
    op.drop_index(op.f('ix_assessment_tenant_id'), table_name='assessment')
    op.drop_index(op.f('ix_assessment_parent_aiia_id'), table_name='assessment')
    op.drop_table('assessment')
    op.drop_index(op.f('ix_use_case_tenant_id'), table_name='use_case')
    op.drop_index(op.f('ix_use_case_system_id'), table_name='use_case')
    op.drop_index(op.f('ix_use_case_state'), table_name='use_case')
    op.drop_table('use_case')
    op.drop_index(op.f('ix_system_tenant_id'), table_name='system')
    op.drop_index(op.f('ix_system_catalogue_vendor_id'), table_name='system')
    op.drop_index(op.f('ix_system_catalogue_product_id'), table_name='system')
    op.drop_table('system')
    op.drop_index(op.f('ix_product_approval_tenant_id'), table_name='product_approval')
    op.drop_index(op.f('ix_product_approval_catalogue_product_id'), table_name='product_approval')
    op.drop_table('product_approval')
    op.drop_index(op.f('ix_catalogue_product_risk_risk_id'), table_name='catalogue_product_risk')
    op.drop_index(op.f('ix_catalogue_product_risk_product_id'), table_name='catalogue_product_risk')
    op.drop_table('catalogue_product_risk')
    op.drop_index(op.f('ix_catalogue_fact_product_id'), table_name='catalogue_fact')
    op.drop_table('catalogue_fact')
    op.drop_index(op.f('ix_vendor_approval_tenant_id'), table_name='vendor_approval')
    op.drop_index(op.f('ix_vendor_approval_catalogue_vendor_id'), table_name='vendor_approval')
    op.drop_table('vendor_approval')
    op.drop_index(op.f('ix_risk_control_map_risk_id'), table_name='risk_control_map')
    op.drop_index(op.f('ix_risk_control_map_control_id'), table_name='risk_control_map')
    op.drop_table('risk_control_map')
    op.drop_index(op.f('ix_membership_user_id'), table_name='membership')
    op.drop_index(op.f('ix_membership_tenant_id'), table_name='membership')
    op.drop_table('membership')
    op.drop_index(op.f('ix_evidence_tenant_id'), table_name='evidence')
    op.drop_index(op.f('ix_evidence_sha256'), table_name='evidence')
    op.drop_table('evidence')
    op.drop_index(op.f('ix_control_framework_map_framework'), table_name='control_framework_map')
    op.drop_index(op.f('ix_control_framework_map_control_id'), table_name='control_framework_map')
    op.drop_table('control_framework_map')
    op.drop_index(op.f('ix_catalogue_product_vendor_id'), table_name='catalogue_product')
    op.drop_table('catalogue_product')
    op.drop_index(op.f('ix_audit_event_tenant_id'), table_name='audit_event')
    op.drop_index(op.f('ix_audit_event_occurred_at'), table_name='audit_event')
    op.drop_index(op.f('ix_audit_event_entity_id'), table_name='audit_event')
    op.drop_index(op.f('ix_audit_event_action'), table_name='audit_event')
    op.drop_table('audit_event')
    op.drop_table('tenant')
    op.drop_index(op.f('ix_risk_layer'), table_name='risk')
    op.drop_table('risk')
    op.drop_table('control')
    op.drop_table('catalogue_vendor')
    op.drop_index(op.f('ix_app_user_email'), table_name='app_user')
    op.drop_index(op.f('ix_app_user_cognito_sub'), table_name='app_user')
    op.drop_table('app_user')
    # ### end Alembic commands ###
