"""aiia_core_migration

Revision ID: 18cdd5bd715c
Revises: 476d462a2a9c
Create Date: 2026-06-17 22:13:28.454255

Schema groundwork for the AIIA core sprint (Phase A) — see
docs/AIIA_DESIGN.md §13 and sprints/SPRINT_AIIA.md WI-1 for the design
rationale. Autogenerated, then hand-edited per CLAUDE.md §4: reused-enum
``create_type=False`` (the project convention — see
c319cbc6fd5b_add_governance_and_product_taxonomy.py), tier_snapshot /
classification_version backfilled from each use case's current
Classification before the NOT NULL constraint (fails loudly if a use case
has no current snapshot — a data-integrity bug, not something to paper
over), tenant_id backfilled on the two join tables before RLS is enabled,
and the uq_one_aiia_per_use_case partial index evolved to be is_current-aware
now that the column exists. Unrelated drift detected by autogenerate
(stray index toggles on eu_operator_role/hosting_model/usage_context/
data_category/affected_party/decision_tree) is intentionally NOT included
here — out of scope for this sprint.
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


revision: str = '18cdd5bd715c'
down_revision: str | Sequence[str] | None = '476d462a2a9c'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # --- 1. New reference table: assessment_section_template -------------------
    op.create_table(
        'assessment_section_template',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('type', postgresql.ENUM(name='assessment_type', create_type=False), nullable=False),
        sa.Column('tier', postgresql.ENUM(name='eu_ai_act_tier', create_type=False), nullable=False),
        sa.Column('section_key', sa.String(length=120), nullable=False),
        sa.Column('title', sa.String(length=255), nullable=False),
        sa.Column('applicability', sa.Enum('REQUIRED', 'RECOMMENDED', 'NOT_APPLICABLE', name='section_applicability'), nullable=False),
        sa.Column('prompt', sa.Text(), nullable=True),
        sa.Column('iso_42005_clause', sa.String(length=120), nullable=True),
        sa.Column('aiia_target_section_key', sa.String(length=120), nullable=True),
        sa.Column('sort_order', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('type', 'tier', 'section_key', name='uq_section_template'),
    )
    op.create_index(op.f('ix_assessment_section_template_tier'), 'assessment_section_template', ['tier'], unique=False)
    op.create_index(op.f('ix_assessment_section_template_type'), 'assessment_section_template', ['type'], unique=False)
    # Global reference table (no tenant_id) — no RLS, matches control/risk library convention.

    # --- 2. assessment: tier_snapshot, classification_version, is_current, ----
    #        lock_version, created_by
    op.add_column('assessment', sa.Column('tier_snapshot', postgresql.ENUM(name='eu_ai_act_tier', create_type=False), nullable=True))
    op.add_column('assessment', sa.Column('classification_version', sa.Integer(), nullable=True))
    op.add_column('assessment', sa.Column('is_current', sa.Boolean(), nullable=True))
    op.add_column('assessment', sa.Column('lock_version', sa.Integer(), nullable=True))
    op.add_column('assessment', sa.Column('created_by', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'assessment', 'app_user', ['created_by'], ['id'], ondelete='SET NULL')

    # Backfill from each use case's CURRENT classification snapshot. Assumes
    # every use case has one (true under auto-resolve at use-case creation);
    # if any assessment's use case lacks a current snapshot, tier_snapshot
    # stays NULL and the subsequent SET NOT NULL fails loudly — intentional,
    # surfaces the data-integrity gap rather than silently defaulting.
    op.execute("""
        UPDATE assessment a
        SET tier_snapshot = c.tier,
            classification_version = c.version
        FROM classification c
        WHERE c.use_case_id = a.use_case_id AND c.is_current = true
    """)
    op.execute("UPDATE assessment SET is_current = true WHERE is_current IS NULL")
    op.execute("UPDATE assessment SET lock_version = 0 WHERE lock_version IS NULL")

    op.alter_column('assessment', 'tier_snapshot', nullable=False)
    op.alter_column('assessment', 'classification_version', nullable=False)
    op.alter_column('assessment', 'is_current', nullable=False, server_default=sa.text('true'))
    op.alter_column('assessment', 'lock_version', nullable=False, server_default='0')
    op.create_index(op.f('ix_assessment_is_current'), 'assessment', ['is_current'], unique=False)

    # uq_one_aiia_per_use_case evolves to be is_current-aware now that the
    # column exists (design doc §8.1) — same index name, hand-managed,
    # already excluded from autogenerate via alembic/env.py include_object.
    op.execute("DROP INDEX IF EXISTS uq_one_aiia_per_use_case")
    op.execute("""
        CREATE UNIQUE INDEX uq_one_aiia_per_use_case
        ON assessment (use_case_id)
        WHERE type = 'AIIA' AND is_current
    """)

    # --- 3. assessment_item: section_key, residuals, selection_basis, --------
    #        source_ref, created_by, lock_version; risk_id FK hardening
    op.add_column('assessment_item', sa.Column('section_key', sa.String(length=120), nullable=True))
    op.add_column('assessment_item', sa.Column('residual_likelihood', sa.Integer(), nullable=True))
    op.add_column('assessment_item', sa.Column('residual_severity', sa.Integer(), nullable=True))
    op.add_column('assessment_item', sa.Column('selection_basis', sa.Text(), nullable=True))
    op.add_column('assessment_item', sa.Column('source_ref', sa.String(length=255), nullable=True))
    op.add_column('assessment_item', sa.Column('created_by', sa.UUID(), nullable=True))
    op.add_column('assessment_item', sa.Column('lock_version', sa.Integer(), nullable=True))
    op.execute("UPDATE assessment_item SET lock_version = 0 WHERE lock_version IS NULL")
    op.alter_column('assessment_item', 'lock_version', nullable=False, server_default='0')
    op.create_index(op.f('ix_assessment_item_section_key'), 'assessment_item', ['section_key'], unique=False)
    op.create_foreign_key(None, 'assessment_item', 'app_user', ['created_by'], ['id'], ondelete='SET NULL')

    # risk_id FK: SET NULL -> RESTRICT (a still-AI_SUGGESTED item's only
    # substance is this FK; library deletion must not silently orphan it).
    op.drop_constraint(op.f('assessment_item_risk_id_fkey'), 'assessment_item', type_='foreignkey')
    op.create_foreign_key(None, 'assessment_item', 'risk', ['risk_id'], ['id'], ondelete='RESTRICT')

    # --- 4. assessment_item_control: tenant_id + RLS, dedup constraint, -------
    #        control_id FK hardening
    op.add_column('assessment_item_control', sa.Column('tenant_id', sa.UUID(), nullable=True))
    op.execute("""
        UPDATE assessment_item_control aic
        SET tenant_id = ai.tenant_id
        FROM assessment_item ai
        WHERE ai.id = aic.item_id
    """)
    op.alter_column('assessment_item_control', 'tenant_id', nullable=False)
    op.create_index(op.f('ix_assessment_item_control_tenant_id'), 'assessment_item_control', ['tenant_id'], unique=False)
    op.create_foreign_key(None, 'assessment_item_control', 'tenant', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.create_unique_constraint('uq_assessment_item_control', 'assessment_item_control', ['item_id', 'control_id'])

    # control_id FK: CASCADE -> RESTRICT (deleting a library control must not
    # silently strip coverage records — that's a loss of audit evidence).
    op.drop_constraint(op.f('assessment_item_control_control_id_fkey'), 'assessment_item_control', type_='foreignkey')
    op.create_foreign_key(None, 'assessment_item_control', 'control', ['control_id'], ['id'], ondelete='RESTRICT')

    # --- 5. assessment_item_evidence: tenant_id + RLS --------------------------
    op.add_column('assessment_item_evidence', sa.Column('tenant_id', sa.UUID(), nullable=True))
    op.execute("""
        UPDATE assessment_item_evidence aie
        SET tenant_id = ai.tenant_id
        FROM assessment_item ai
        WHERE ai.id = aie.item_id
    """)
    op.alter_column('assessment_item_evidence', 'tenant_id', nullable=False)
    op.create_index(op.f('ix_assessment_item_evidence_tenant_id'), 'assessment_item_evidence', ['tenant_id'], unique=False)
    op.create_foreign_key(None, 'assessment_item_evidence', 'tenant', ['tenant_id'], ['id'], ondelete='CASCADE')

    # --- 6. RLS parity on the two join tables (design doc §13) ----------------
    for table in ("assessment_item_control", "assessment_item_evidence"):
        op.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY")
        op.execute(f"""
            CREATE POLICY tenant_isolation ON {table}
            USING (tenant_id = current_setting('app.current_tenant', true)::uuid)
        """)


def downgrade() -> None:
    for table in ("assessment_item_control", "assessment_item_evidence"):
        op.execute(f"DROP POLICY IF EXISTS tenant_isolation ON {table}")
        op.execute(f"ALTER TABLE {table} DISABLE ROW LEVEL SECURITY")

    op.drop_constraint(None, 'assessment_item_evidence', type_='foreignkey')
    op.drop_index(op.f('ix_assessment_item_evidence_tenant_id'), table_name='assessment_item_evidence')
    op.drop_column('assessment_item_evidence', 'tenant_id')

    op.drop_constraint(None, 'assessment_item_control', type_='foreignkey')
    op.create_foreign_key(op.f('assessment_item_control_control_id_fkey'), 'assessment_item_control', 'control', ['control_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('uq_assessment_item_control', 'assessment_item_control', type_='unique')
    op.drop_constraint(None, 'assessment_item_control', type_='foreignkey')
    op.drop_index(op.f('ix_assessment_item_control_tenant_id'), table_name='assessment_item_control')
    op.drop_column('assessment_item_control', 'tenant_id')

    op.drop_constraint(None, 'assessment_item', type_='foreignkey')
    op.create_foreign_key(op.f('assessment_item_risk_id_fkey'), 'assessment_item', 'risk', ['risk_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint(None, 'assessment_item', type_='foreignkey')
    op.drop_index(op.f('ix_assessment_item_section_key'), table_name='assessment_item')
    op.drop_column('assessment_item', 'lock_version')
    op.drop_column('assessment_item', 'created_by')
    op.drop_column('assessment_item', 'source_ref')
    op.drop_column('assessment_item', 'selection_basis')
    op.drop_column('assessment_item', 'residual_severity')
    op.drop_column('assessment_item', 'residual_likelihood')
    op.drop_column('assessment_item', 'section_key')

    op.execute("DROP INDEX IF EXISTS uq_one_aiia_per_use_case")
    op.execute("""
        CREATE UNIQUE INDEX uq_one_aiia_per_use_case
        ON assessment (use_case_id)
        WHERE type = 'AIIA'
    """)
    op.drop_index(op.f('ix_assessment_is_current'), table_name='assessment')
    op.drop_constraint(None, 'assessment', type_='foreignkey')
    op.drop_column('assessment', 'created_by')
    op.drop_column('assessment', 'lock_version')
    op.drop_column('assessment', 'is_current')
    op.drop_column('assessment', 'classification_version')
    op.drop_column('assessment', 'tier_snapshot')

    op.drop_index(op.f('ix_assessment_section_template_type'), table_name='assessment_section_template')
    op.drop_index(op.f('ix_assessment_section_template_tier'), table_name='assessment_section_template')
    op.drop_table('assessment_section_template')
