"""governance_role_model

Revision ID: 8b7d2f48a456
Revises: 099104f68fc0
Create Date: 2026-06-13 07:56:51.564180
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '8b7d2f48a456'
down_revision: str | Sequence[str] | None = '099104f68fc0'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('governance_role',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('line_of_defence', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_governance_role_key'), 'governance_role', ['key'], unique=True)
    op.create_table('governance_role_conflict',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('role_a_id', sa.UUID(), nullable=False),
    sa.Column('role_b_id', sa.UUID(), nullable=False),
    sa.CheckConstraint('role_a_id < role_b_id', name='ck_governance_role_conflict_canonical'),
    sa.ForeignKeyConstraint(['role_a_id'], ['governance_role.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['role_b_id'], ['governance_role.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role_a_id', 'role_b_id', name='uq_governance_role_conflict')
    )
    op.create_index(op.f('ix_governance_role_conflict_role_a_id'), 'governance_role_conflict', ['role_a_id'], unique=False)
    op.create_index(op.f('ix_governance_role_conflict_role_b_id'), 'governance_role_conflict', ['role_b_id'], unique=False)
    op.create_table('governance_role_assignment',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('membership_id', sa.UUID(), nullable=False),
    sa.Column('governance_role_id', sa.UUID(), nullable=False),
    sa.Column('granted_by_membership_id', sa.UUID(), nullable=True),
    sa.Column('granted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['governance_role_id'], ['governance_role.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['granted_by_membership_id'], ['membership.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['membership_id'], ['membership.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'membership_id', 'governance_role_id', name='uq_governance_role_assignment')
    )
    op.create_index(op.f('ix_governance_role_assignment_governance_role_id'), 'governance_role_assignment', ['governance_role_id'], unique=False)
    op.create_index(op.f('ix_governance_role_assignment_granted_by_membership_id'), 'governance_role_assignment', ['granted_by_membership_id'], unique=False)
    op.create_index(op.f('ix_governance_role_assignment_membership_id'), 'governance_role_assignment', ['membership_id'], unique=False)
    op.create_index(op.f('ix_governance_role_assignment_tenant_id'), 'governance_role_assignment', ['tenant_id'], unique=False)
    # ### end Alembic commands ###

    # --- hand-added: RLS on governance_role_assignment ----------------------------
    # governance_role and governance_role_conflict are platform reference tables
    # (no tenant_id) — no RLS. governance_role_assignment is tenant data and must
    # be isolated by tenant, exactly like every other tenant-scoped table.
    op.execute("ALTER TABLE governance_role_assignment ENABLE ROW LEVEL SECURITY")
    op.execute("""
        CREATE POLICY tenant_isolation ON governance_role_assignment
        USING (tenant_id = current_setting('app.current_tenant', true)::uuid)
    """)

    # --- hand-added: grants -------------------------------------------------------
    # irontrustai_app gets SELECT/INSERT/UPDATE/DELETE on ALL new tables via
    # ALTER DEFAULT PRIVILEGES in 00_roles.sh. We narrow governance_role_assignment
    # to INSERT/DELETE only — grants are immutable (revoke is a row delete, not an
    # UPDATE). The reference tables (governance_role, governance_role_conflict) need
    # no narrowing; they're written only by migrations.
    op.execute(
        "REVOKE UPDATE ON governance_role_assignment FROM irontrustai_app"
    )

    # Give the platform read role visibility into governance for operator dashboards.
    op.execute(
        "GRANT SELECT ON governance_role, governance_role_conflict, "
        "governance_role_assignment TO irontrustai_platform_ro"
    )

    # --- hand-added: governance role catalogue seed (deployment data) -------------
    # The five governance roles are deployment data — their keys are referenced by
    # application code (SoD checks, endpoint logic). Seeded here so every
    # environment gets them on `alembic upgrade head`. The seed script
    # (scripts/seed/seed_governance_roles.py) is idempotent and safe to re-run.
    op.execute("""
        INSERT INTO governance_role (id, key, name, description, line_of_defence)
        VALUES
          (gen_random_uuid(), 'system_owner',
           'System Owner',
           'Accountable for an AI system end-to-end. Initiates and steers the '
           'impact assessment process. First line of defence.',
           1),
          (gen_random_uuid(), 'contributor',
           'Contributor',
           'Active participant in assessment work: provides evidence, fills in '
           'impact assessment items, drives remediation. First line of defence. '
           'May be co-held with system_owner.',
           1),
          (gen_random_uuid(), 'reviewer',
           'Reviewer',
           'Independent quality-gate reviewer for assessment outputs. '
           'Second line of defence. Conflicts with authoriser.',
           2),
          (gen_random_uuid(), 'authoriser',
           'Authoriser',
           'Provides final sign-off / approval on assessed AI systems. '
           'Second line of defence. Conflicts with reviewer.',
           2),
          (gen_random_uuid(), 'auditor',
           'Auditor',
           'Read-only independent oversight across all assessment artefacts. '
           'Third line of defence. Conflicts with all first- and second-line roles.',
           3)
    """)

    # --- SoD conflict matrix seed ------------------------------------------------
    # 9 conflicting pairs: every cross-line pair plus reviewer×authoriser (same
    # line, separated). The only COMPOSABLE pair (system_owner + contributor) is
    # deliberately absent. Canonical ordering (role_a_id < role_b_id as UUID
    # comparison) is enforced by the check constraint; LEAST/GREATEST here ensure
    # the INSERT always satisfies it regardless of UUID assignment order.
    conflict_pairs = [
        # line-1 × line-2
        ("system_owner", "reviewer"),
        ("system_owner", "authoriser"),
        ("contributor", "reviewer"),
        ("contributor", "authoriser"),
        # line-1 × line-3
        ("system_owner", "auditor"),
        ("contributor", "auditor"),
        # within line-2 (separated)
        ("reviewer", "authoriser"),
        # line-2 × line-3
        ("reviewer", "auditor"),
        ("authoriser", "auditor"),
    ]
    for key_a, key_b in conflict_pairs:
        op.execute(f"""
            INSERT INTO governance_role_conflict (id, role_a_id, role_b_id)
            SELECT
              gen_random_uuid(),
              LEAST(
                (SELECT id FROM governance_role WHERE key = '{key_a}'),
                (SELECT id FROM governance_role WHERE key = '{key_b}')
              ),
              GREATEST(
                (SELECT id FROM governance_role WHERE key = '{key_a}'),
                (SELECT id FROM governance_role WHERE key = '{key_b}')
              )
        """)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP POLICY IF EXISTS tenant_isolation ON governance_role_assignment")
    op.execute("ALTER TABLE governance_role_assignment DISABLE ROW LEVEL SECURITY")

    op.drop_index(op.f('ix_governance_role_assignment_tenant_id'), table_name='governance_role_assignment')
    op.drop_index(op.f('ix_governance_role_assignment_membership_id'), table_name='governance_role_assignment')
    op.drop_index(op.f('ix_governance_role_assignment_granted_by_membership_id'), table_name='governance_role_assignment')
    op.drop_index(op.f('ix_governance_role_assignment_governance_role_id'), table_name='governance_role_assignment')
    op.drop_table('governance_role_assignment')
    op.drop_index(op.f('ix_governance_role_conflict_role_b_id'), table_name='governance_role_conflict')
    op.drop_index(op.f('ix_governance_role_conflict_role_a_id'), table_name='governance_role_conflict')
    op.drop_table('governance_role_conflict')
    op.drop_index(op.f('ix_governance_role_key'), table_name='governance_role')
    op.drop_table('governance_role')
    # ### end Alembic commands ###
