"""add legal_ref to eu ai act taxonomy

Revision ID: 8eda654f48eb
Revises: c319cbc6fd5b
Create Date: 2026-05-31 20:56:58.677994
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '8eda654f48eb'
down_revision: str | Sequence[str] | None = 'c319cbc6fd5b'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('eu_ai_act_subcategory', sa.Column('legal_ref', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('eu_ai_act_subcategory', 'legal_ref')
    # ### end Alembic commands ###
