"""add governance and product taxonomy

Revision ID: c319cbc6fd5b
Revises: c53be9b832eb
Create Date: 2026-05-31 13:46:32.100361
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


revision: str = 'c319cbc6fd5b'
down_revision: str | Sequence[str] | None = 'c53be9b832eb'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('eu_ai_act_category',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('product_category',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['product_category.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index(op.f('ix_product_category_parent_id'), 'product_category', ['parent_id'], unique=False)
    op.create_table('eu_ai_act_subcategory',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('tier', postgresql.ENUM(name='eu_ai_act_tier', create_type=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['eu_ai_act_category.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index(op.f('ix_eu_ai_act_subcategory_category_id'), 'eu_ai_act_subcategory', ['category_id'], unique=False)
    op.create_index(op.f('ix_eu_ai_act_subcategory_tier'), 'eu_ai_act_subcategory', ['tier'], unique=False)
    op.create_table('product_category_eu_mapping',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('product_category_id', sa.UUID(), nullable=False),
    sa.Column('eu_ai_act_subcategory_id', sa.UUID(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['eu_ai_act_subcategory_id'], ['eu_ai_act_subcategory.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_category_id'], ['product_category.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_category_id', 'eu_ai_act_subcategory_id', name='uq_product_category_eu_mapping')
    )
    op.create_index(op.f('ix_product_category_eu_mapping_eu_ai_act_subcategory_id'), 'product_category_eu_mapping', ['eu_ai_act_subcategory_id'], unique=False)
    op.create_index(op.f('ix_product_category_eu_mapping_product_category_id'), 'product_category_eu_mapping', ['product_category_id'], unique=False)
    op.create_table('product_category_membership',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('catalogue_product_id', sa.UUID(), nullable=False),
    sa.Column('product_category_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['catalogue_product_id'], ['catalogue_product.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_category_id'], ['product_category.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('catalogue_product_id', 'product_category_id', name='uq_product_category_membership')
    )
    op.create_index(op.f('ix_product_category_membership_catalogue_product_id'), 'product_category_membership', ['catalogue_product_id'], unique=False)
    op.create_index(op.f('ix_product_category_membership_product_category_id'), 'product_category_membership', ['product_category_id'], unique=False)
    op.add_column('catalogue_product', sa.Column('logo_url', sa.Text(), nullable=True))
    op.add_column('catalogue_vendor', sa.Column('logo_url', sa.Text(), nullable=True))
    op.add_column('use_case', sa.Column('eu_ai_act_subcategory_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_use_case_eu_ai_act_subcategory_id'), 'use_case', ['eu_ai_act_subcategory_id'], unique=False)
    op.create_foreign_key(None, 'use_case', 'eu_ai_act_subcategory', ['eu_ai_act_subcategory_id'], ['id'], ondelete='RESTRICT')
    
    op.execute("""
        CREATE UNIQUE INDEX uq_one_primary_eu_mapping
        ON product_category_eu_mapping (product_category_id)
        WHERE is_primary = true
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP INDEX IF EXISTS uq_one_primary_eu_mapping")
    op.drop_constraint(None, 'use_case', type_='foreignkey')
    op.drop_index(op.f('ix_use_case_eu_ai_act_subcategory_id'), table_name='use_case')
    op.drop_column('use_case', 'eu_ai_act_subcategory_id')
    op.drop_column('catalogue_vendor', 'logo_url')
    op.drop_column('catalogue_product', 'logo_url')
    op.drop_index(op.f('ix_product_category_membership_product_category_id'), table_name='product_category_membership')
    op.drop_index(op.f('ix_product_category_membership_catalogue_product_id'), table_name='product_category_membership')
    op.drop_table('product_category_membership')
    op.drop_index(op.f('ix_product_category_eu_mapping_product_category_id'), table_name='product_category_eu_mapping')
    op.drop_index(op.f('ix_product_category_eu_mapping_eu_ai_act_subcategory_id'), table_name='product_category_eu_mapping')
    op.drop_table('product_category_eu_mapping')
    op.drop_index(op.f('ix_eu_ai_act_subcategory_tier'), table_name='eu_ai_act_subcategory')
    op.drop_index(op.f('ix_eu_ai_act_subcategory_category_id'), table_name='eu_ai_act_subcategory')
    op.drop_table('eu_ai_act_subcategory')
    op.drop_index(op.f('ix_product_category_parent_id'), table_name='product_category')
    op.drop_table('product_category')
    op.drop_table('eu_ai_act_category')
    # ### end Alembic commands ###
