"""add reference_url to risk

Revision ID: c53be9b832eb
Revises: 182010f00859
Create Date: 2026-05-30 22:27:39.522338
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'c53be9b832eb'
down_revision: str | Sequence[str] | None = '182010f00859'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('risk', sa.Column('reference_url', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('risk', 'reference_url')
    # ### end Alembic commands ###
