"""operator rbac

Revision ID: cef7211ddfe4
Revises: 7b4d1c391113
Create Date: 2026-06-06 10:21:34.148864
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'cef7211ddfe4'
down_revision: str | Sequence[str] | None = '7b4d1c391113'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('operator',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('cognito_sub', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'DISABLED', name='operator_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_operator_cognito_sub'), 'operator', ['cognito_sub'], unique=True)
    op.create_index(op.f('ix_operator_email'), 'operator', ['email'], unique=False)
    op.create_table('permission',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_permission_key'), 'permission', ['key'], unique=True)
    op.create_table('role',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_role_key'), 'role', ['key'], unique=True)
    op.create_table('operator_role',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('operator_id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('granted_by_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['granted_by_id'], ['operator.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['operator_id'], ['operator.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('operator_id', 'role_id', name='uq_operator_role')
    )
    op.create_index(op.f('ix_operator_role_granted_by_id'), 'operator_role', ['granted_by_id'], unique=False)
    op.create_index(op.f('ix_operator_role_operator_id'), 'operator_role', ['operator_id'], unique=False)
    op.create_index(op.f('ix_operator_role_role_id'), 'operator_role', ['role_id'], unique=False)
    op.create_table('role_permission',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('permission_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permission.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role_id', 'permission_id', name='uq_role_permission')
    )
    op.create_index(op.f('ix_role_permission_permission_id'), 'role_permission', ['permission_id'], unique=False)
    op.create_index(op.f('ix_role_permission_role_id'), 'role_permission', ['role_id'], unique=False)
    # ### end Alembic commands ###

    # --- hand-added: GRANTs to the platform DB roles ---------------------------
    # Placed in the same migration as the tables so the grants reproduce with the
    # schema in every environment and never depend on 00_roles.sh timing. The
    # roles themselves must already exist (created in 00_roles.sh) before this
    # migration runs. No REVOKE is needed in downgrade: dropping the tables drops
    # the privileges granted on them.

    # Read path. get_current_operator resolves an operator + their effective
    # permissions on every platform request. SELECT only.
    op.execute(
        "GRANT SELECT ON operator, operator_role, role, permission, role_permission "
        "TO irontrustai_platform_ro"
    )

    # Operator-creation path (create-operator CLI). Creates operators and assigns
    # roles, reading `role` to resolve the grant. Create-and-read only — the
    # platform-plane analogue of irontrustai_provisioner.
    op.execute(
        "GRANT SELECT, INSERT ON operator, operator_role "
        "TO irontrustai_operator_provisioner"
    )
    op.execute("GRANT SELECT ON role TO irontrustai_operator_provisioner")

    # --- hand-added: catalogue seed (deployment data) --------------------------
    # The single permission + role this sprint needs. The keys are the literals
    # code references (require_permission("tenant:provision")), so they are seeded
    # here rather than created at runtime. created_at/updated_at fall to their
    # server_default now(); id needs an explicit value.
    # (gen_random_uuid() is core in PostgreSQL 13+. On <13, CREATE EXTENSION pgcrypto.)
    op.execute(
        "INSERT INTO permission (id, key, description) "
        "VALUES (gen_random_uuid(), 'tenant:provision', "
        "'Provision a new tenant and its first owner')"
    )
    op.execute(
        "INSERT INTO role (id, key, description) "
        "VALUES (gen_random_uuid(), 'provisioner', 'Can provision new tenants')"
    )
    op.execute(
        "INSERT INTO role_permission (id, role_id, permission_id) "
        "SELECT gen_random_uuid(), "
        "(SELECT id FROM role WHERE key = 'provisioner'), "
        "(SELECT id FROM permission WHERE key = 'tenant:provision')"
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_role_permission_role_id'), table_name='role_permission')
    op.drop_index(op.f('ix_role_permission_permission_id'), table_name='role_permission')
    op.drop_table('role_permission')
    op.drop_index(op.f('ix_operator_role_role_id'), table_name='operator_role')
    op.drop_index(op.f('ix_operator_role_operator_id'), table_name='operator_role')
    op.drop_index(op.f('ix_operator_role_granted_by_id'), table_name='operator_role')
    op.drop_table('operator_role')
    op.drop_index(op.f('ix_role_key'), table_name='role')
    op.drop_table('role')
    op.drop_index(op.f('ix_permission_key'), table_name='permission')
    op.drop_table('permission')
    op.drop_index(op.f('ix_operator_email'), table_name='operator')
    op.drop_index(op.f('ix_operator_cognito_sub'), table_name='operator')
    op.drop_table('operator')
    # ### end Alembic commands ###

    # --- hand-added: drop the enum type the table left behind ------------------
    # Autogenerate CREATEs operator_status on the way up (inside create_table) but
    # does NOT drop it on the way down. Without this, a re-upgrade fails with
    # "type operator_status already exists". The seeded rows and the grants need
    # no explicit cleanup here — they were removed when their tables were dropped.
    op.execute("DROP TYPE operator_status")